#!/bin/bash
set -Eeo pipefail

fallback_server="127.0.0.1:5002"
fallback_config="/opt/xray/config.json"

if [[ -z "${server}" ]];
then
  server=${fallback_server}
fi

if [[ -z "${config}" ]];
then
  config=${fallback_config}
fi

# Space-separated lists of tags to exclude from the corresponding graphs.
# Override via env.exclude_users / env.exclude_inbounds / env.exclude_outbounds in munin config.
exclude_users="${exclude_users:-}"
exclude_inbounds="${exclude_inbounds:-api}"
exclude_outbounds="${exclude_outbounds:-block dns}"

request=$(basename "$0" | sed 's/^xray_//g')

if [[ $1 == "suggest" ]];
then
  echo "user"
  echo "inbound"
  echo "outbound"
  exit 0
fi

if ! command -v jq &> /dev/null
then
    echo "'jq' not found, please install it!"  >&2
    exit 255
fi

if ! command -v md5sum &> /dev/null
then
    echo "'md5sum' not found, please install it!"  >&2
    exit 255
fi

if ! command -v curl &> /dev/null
then
    echo "'curl' not found, please install it!"  >&2
    exit 255
fi

first=0
printTagConfig()
{
    echo "${1}_dl.min 0"
    echo "${1}_dl.graph no"
    echo "${1}_dl.label ${2}"
    echo "${1}_dl.type DERIVE"
    echo "${1}_dl.cdef ${1}_dl,8,*"
    if [[ $first -eq 0 ]];
    then
      echo "${1}_dl.draw AREA"
      true
    else
      echo "${1}_dl.draw STACK"
    fi
    echo "${1}_ul.label ${2}"
    echo "${1}_ul.type DERIVE"
    echo "${1}_ul.negative ${1}_dl"
    echo "${1}_ul.min 0"
    echo "${1}_ul.cdef ${1}_ul,8,*"
    if [[ $first -eq 0 ]];
    then
      true
      echo "${1}_ul.draw AREA"
    else
      echo "${1}_ul.draw STACK"
    fi
    first=1
}

if [[ ${request} == "user" ]]
then
  tags=$(cat ${config} | jq -r "[.inbounds[] | .settings | .clients[]? | .email] | unique | .[]")
  for e in ${exclude_users}
  do
    tags=$(echo ${tags} | sed "s/${e}//g")
  done
fi

data=$(curl -s "http://${server}/debug/vars" | jq -r ".stats")

if [[ ${request} == "inbound" ]]
then
  tags=$(echo "${data}" | jq -r ".inbound | keys[]")
  for e in ${exclude_inbounds}
  do
    tags=$(echo ${tags} | sed "s/${e}//g")
  done
fi

if [[ ${request} == "outbound" ]]
then
  tags=$(
    {
      echo "${data}" | jq -r '.outbound | keys[]'
      jq -r '[.inbounds[]?.settings.clients[]?.reverse.tag // empty] | .[]' "${config}"
    } | sort -u
  )

  for e in ${exclude_outbounds}
  do
    tags=$(echo "${tags}" | sed "s/${e}//g")
  done
fi

getOrder()
{
  order=""
  for tag in ${tags}
  do
    hashedTag=$(echo ${tag} | md5sum | head -c8)
    order="${order} x${hashedTag}"
  done
}

if [[ $1 == "config" ]];
then
    getOrder
    echo "graph_title Xray: Traffic per ${request}"
    echo "graph_order ${order}"
    echo "graph_args --base 1000"
    echo "graph_vlabel bits in (-) / out (+) per ${graph_period}"
    for tag in ${tags}
    do
      hashedTag=$(echo ${tag} | md5sum | head -c8)
      printTagConfig x$hashedTag $tag
    done
    exit 0
fi


printTagTraffic()
{
  value=$(echo "${data}" | jq -r ".\"${1}\".\"${2}\".\"${3}\"")
  if [[ ${value} == "null" ]];
  then
    value="0"
  fi
  if [[ -z ${value} ]]
  then
    echo "0"
  else
    ## not dangerous, we trust the content of the config file
    eval valueClear=${value}
    echo ${valueClear}
  fi
}

for tag in ${tags}
do
  hashedTag=$(echo ${tag} | md5sum | head -c8)
  printf "x${hashedTag}_dl.value "
  printTagTraffic ${request} ${tag} downlink
  printf "x${hashedTag}_ul.value "
  printTagTraffic ${request} ${tag} uplink
done

